#开发配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.127.128:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.127.128
    port: 6380
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.lagou.rcache.entity
  mapperLocations: classpath:mapper/*.xml


